### ISSUE TITLE
Probles instlling elevation

### ISSUE THREAD

**Issue by supertobi** [bopen/elevation#20]
Hi,

I think this is not a software but a user problem. I tried to install elevation

```
pip install elevation

sudo add-apt-repository ppa:ubuntugis/ppa
sudo apt-get update
sudo apt-get install gdal-bin
```

But if I nor run 

```
$ eio selfcheck
```

I just get

```
eio: Command not found
```

What is missing?

**Comment by alexamici** [comment]
Indeed this is a user support question and it is not appropriate for the GitHub issue tracker. Please read carefully [the project documentation](http://elevation.bopen.eu) and as it is suggested there, if you still can't solve your problem [ask user support questions on StackOverflow](http://stackoverflow.com/questions/ask).

I'll close the issue.
