### ISSUE TITLE
the elevation.clean() command cannot remove spools

### ISSUE THREAD

**Issue by Pielewuiter** [bopen/elevation#21]
Hi, I'm using rPython to run the script from within R (on Ubuntu 14.04). That seems to work fine, but for some reason, the elevation.clean() procedure throws an error (breaking my iteration in R).
I get: 
```
make: Entering directory `/home/user/.cache/elevation/SRTM1'
find cache -size 0 -name "*.tif" -delete
rm -f spool/*
rm: cannot remove ‘spool/N41’: Is a directory
make: *** [clean] Error 1
make: Leaving directory `/home/user/.cache/elevation/SRTM1'
```
I do not know whether this problem is related to the script or to my system setup, though.. 
Any thoughts?

**Comment by alexamici** [comment]
@Pielewuiter indeed this looks like a genuine bug. I had to do a change in the structure of the spool and forgot to test the clean command. Thanks.

**Comment by alexamici** [comment]
@Pielewuiter can you test if latest master fixes the problem for you?
```
$ pip install https://github.com/bopen/elevation/archive/master.zip
```
Thanks.

**Comment by Pielewuiter** [comment]
@alexamici yep, it's running smooth for me now. Thanks for your quick response!
