### ISSUE TITLE
SRTM 30m data coverage

### ISSUE THREAD

**Issue by leroygr** [bopen/elevation#29]
Hello,

I have a question regarding the coverage of srtm 30m data that are downloaded from S3. From your README, it mentions that the 30m data comes from  [the global datasets SRTM 30m Global 1 arc second V003 elaborated by NASA and NGA](https://lpdaac.usgs.gov/dataset_discovery/measures/measures_products_table/SRTMGL1_v003). When looking at the link, it says that the spatial extent is "Global (60°N to 56°S, 180°W to 180°E)".

However, I downloaded a tile beyond the extent mentioned (skadi/N65/N65E015.hgt.gz) and I do have elevation data in that area that is supposed to be outside the coverage:
![image](https://user-images.githubusercontent.com/1411854/46397555-cd16aa00-c6f2-11e8-974b-6f88198b1ba0.png)

When looking at Mapzen websites, it says that they _provide worldwide basemap coverage sourced from SRTM and other open data projects with several different data formats and varying levels of processing_.

So my guess is that the elevation data downloaded from s3 bucket (skadi) are a mix of different sources and not only the original srtm data. 

Could someone clarify this? 

Thanks a lot,
Greg

**Comment by molind** [comment]
Hi, there is a documentation about the process and datasources used to build skadi dataset.
https://github.com/tilezen/joerd/blob/master/docs/data-sources.md
